name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          # Descargar la versión correcta de Gitleaks
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          curl -Lo gitleaks https://github.com/gitleaks/gitleaks/releases/download/$GITLEAKS_VERSION/gitleaks_${GITLEAKS_VERSION}_linux_x64
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - run: |
          gitleaks detect --source . --no-banner --redact
