name: Secret Scan

on:
  push:
    branches:
      - '**'

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Gitleaks scan on .env1
        uses: zricethezav/gitleaks-action@v1
        with:
          args: "detect --source . --no-git --verbose --redact"
