name: Secret Scan

on:
  push:
    branches:
      - '**'

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run TruffleHog scan using Docker
        run: docker run -v ${{ github.workspace }}:/repo ghcr.io/trufflesecurity/trufflehog:latest filesystem /repo
